### ISSUE TITLE
No implementation found for method saveImageKey

### ISSUE THREAD

**Issue by CollinAlpert** [FiveDotTwelve/save_in_gallery#16]
Hi, I'm getting an exception when trying to save an image on Android. My flutter version is 1.16.3. I am using the latest version of this package. This is the exception:
```
E/flutter (12951): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method saveImageKey on channel com.fdt/save_in_gallery_channel)
E/flutter (12951): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (12951): <asynchronous suspension>
E/flutter (12951): #1      ImageSaver.saveImage (package:save_in_gallery/save_in_gallery.dart:25:43)
```

Am I missing anything?

**Comment by yangancode** [comment]
I also has this problem too!

**Comment by CollinAlpert** [comment]
I found that a hot restart was not enough to apply the plugin. Completely restarting the app fixed the problem for me.
